name: Build

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "15 * * * *"   # hourly (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java and GPG
        uses: actions/setup-java@v4
        with:
          distribution: temurin          # modern replacement for "adopt"
          java-version: '11'
          cache: maven
          # Imports your private key and configures gpg-agent for CI
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}          # ASCII-armored private key block
          gpg-passphrase:  ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} # passphrase

      # Ensure loopback pinentry is allowed for headless signing (belt & suspenders)
      - name: Configure GPG for loopback
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo 'allow-loopback-pinentry' >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent || true
          # Sanity check: list the key (won't print secret material)
          gpg --batch --list-secret-keys --keyid-format LONG

      - name: Build & verify (signs at verify phase)
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn --no-transfer-progress -B --update-snapshots clean verify
