name: Build

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Java + import GPG
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase:  ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Allow loopback pinentry + show key
        run: |
          mkdir -p ~/.gnupg && chmod 700 ~/.gnupg
          echo 'allow-loopback-pinentry' >> ~/.gnupg/gpg-agent.conf || true
          gpgconf --kill gpg-agent || true
          gpg --batch --list-secret-keys --keyid-format LONG

      - name: Build & Verify (Maven signs at verify)
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: |
          KEYID=$(gpg --batch --with-colons --list-secret-keys \
            | awk -F: '($1=="ssb" && $12 ~ /s/) || ($1=="sec" && $12 ~ /s/){print $5; exit}')
          if [ -z "$KEYID" ]; then
            echo "::error::No signing-capable secret key found in CI keyring."
            exit 1
          fi
          mvn --no-transfer-progress -B --update-snapshots \
            -Dgpg.keyname="$KEYID" \
            clean verify
