name: Build & Deploy (Tag)

on:
  push:
    tags:
      - 'v*'            # only version tags; change to '*' if you want all tags
  workflow_dispatch: {}  # optional: allow manual runs

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java, Maven server, and import GPG
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          # This writes <server id="ossrh"> with id=ossrh
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          # Import the CI signing key & configure gpg-agent
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase:  ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Allow loopback pinentry & show keys
        run: |
          mkdir -p ~/.gnupg && chmod 700 ~/.gnupg
          echo 'allow-loopback-pinentry' >> ~/.gnupg/gpg-agent.conf || true
          gpgconf --kill gpg-agent || true
          echo "== Secret keys (LONG) ==" && gpg --batch --list-secret-keys --keyid-format LONG || true

      - name: Detect signing key (prefers signing subkey)
        id: gpg
        shell: bash
        run: |
          set -euo pipefail
          KEYID=$(gpg --batch --with-colons --list-secret-keys \
            | awk -F: '($1=="ssb" && $12 ~ /s/) || ($1=="sec" && $12 ~ /s/){print $5; exit}')
          if [ -z "$KEYID" ]; then
            echo "::error::No signing-capable secret key found in CI keyring."
            exit 1
          fi
          echo "keyid=$KEYID" >> "$GITHUB_OUTPUT"
          echo "Using signing key: $KEYID"

      - name: Prove we can sign (clearsign test)
        env:
          GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: |
          set -euo pipefail
          echo "test" > /tmp/sign.txt
          gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" \
              --local-user '${{ steps.gpg.outputs.keyid }}' \
              --clearsign /tmp/sign.txt > /tmp/sign.txt.asc
          head -n 3 /tmp/sign.txt.asc || true

      - name: Build & Deploy to Sonatype (staging)
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        run: |
          mvn --no-transfer-progress -B --update-snapshots \
            -Dgpg.keyname='${{ steps.gpg.outputs.keyid }}' \
            clean deploy





