name: Build & Deploy (Tag)

on:
  push:
    tags:
      - 'v*'            # only version tags; change to '*' if you truly want all tags
  workflow_dispatch: {}  # optional: allow manual runs

permissions:
  contents: read        # least privilege; bump to write only if you add GH release steps
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}   # avoid overlapping runs per tag
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')        # belt-and-suspenders guard
    env:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      MAVEN_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

    steps:
      - name: Checkout (full history for SCM)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
          server-id: ossrh                     # matches <id> in distributionManagement
          server-username: MAVEN_USERNAME      # env var names (not secrets directly)
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}           # ASCII-armored
          gpg-passphrase:  ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Build & Deploy
        run: |
          mvn -B --no-transfer-progress \
            -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            -DskipTests=false \
            clean verify deploy

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: |
            **/target/*.jar
            **/target/*.pom
            **/target/*.asc
